# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IndoorNavi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IndoorNavi
  pod 'GCDWebServer', '~> 3.0'

  target 'IndoorNaviTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
